### ISSUE TITLE
Unwanted Exit snapzone event is getting triggered

### ISSUE THREAD

**Issue by Maciej92Zareba** [ExtendRealityLtd/Tilia.Interactions.SnapZone.Unity#191]
### Environment

Tested on Unity 2021.2.19 / 2021.3.0 / 2021.3.2 
Interactables 2.1.0
SnapZone 2.1.0

### Steps to reproduce

1) Create new scene
2) Delete all objects from scene
3) Add default snap zone at 0,0,0 with AutoSnapThrownObject set to true
4) Add default Interactable at 0,3,0
5) Add any way to debug SnapZone events (Enetered, Exited, Activated, Deactivated, Snaped, Unsnaped)

### Expected behavior

There should be following Events Entered->Snaped

### Current behavior

There are following events Entered->Snapped->Exited->Entered

**Comment by thestonefox** [comment]
PR with fix https://github.com/ExtendRealityLtd/Tilia.Interactions.SnapZone.Unity/pull/192
